[package]
name = "perpetual"
version = "0.0.1"
authors = []

[addresses]
perpetual = "0f79aebf9dce333113e6b5dc8e5d90cc0639e2180034a258a92d3d586726b619"

[dev-addresses]

[dependencies.Pyth]
local = "../vendor"

#[dependencies.AptosFramework]
#git = "https://github.com/aptos-labs/aptos-core.git"
#rev = "mainnet"
#subdir = "aptos-move/framework/aptos-framework"


[dependencies.AptosFramework]
local = "../aptos-framework"

[dev-dependencies]
